version: "2"
services:
  noderestapi:
    container_name: noderestapi
    restart: always
    build: .
    ports:
      - "3000:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  varnish:
    ports:
      - 27017:27017
      - 3000 
  
  